AppMsg = {}
--主界面
AppMsg.LoginShow = "LoginShow"
AppMsg.LoginHide = "LoginHide"
AppMsg.DialogShow = "DialogShow"
AppMsg.DialogHide = "DialogHide"
AppMsg.WaitingShow = "WaitingShow"
AppMsg.WaitingHide = "WaitingHide"

AppMsg.MainShow = "MainShow"
AppMsg.UpdatePlayInfo = "UpdatePlayInfo"
AppMsg.MainHide = "MainHide"
AppMsg.RoomShow = "RoomShow"
AppMsg.RoomHide = "RoomHide"
AppMsg.AwardShow = "AwardShow"

AppMsg.PersonalShow = "PersonalShow"
AppMsg.UserHeadShow = "UserHeadShow"
AppMsg.UserHeadHide = "UserHeadHide"
AppMsg.UserNameShow = "UserNameShow"
AppMsg.UserNameHide = "UserNameHide"

AppMsg.SupportShow = "SupportShow"
AppMsg.EmailShow = "EmailShow"
AppMsg.EmailHide = "EmailHide"
AppMsg.EmailDetailShow = "EmailDetailShow"
AppMsg.UpdateEmailInfo = "UpdateEmailInfo"
AppMsg.SettingShow = "SettingShow"
AppMsg.RuleShow = "RuleShow"

AppMsg.BindShow = "BindShow"
AppMsg.BindHide = "BindHide"
AppMsg.DailyShow = "DailyShow"
AppMsg.UpdateDailyInfo = "UpdateDailyInfo"
AppMsg.VipShow = "VipShow"
AppMsg.UpdateVipInfo = "UpdateVipInfo"
AppMsg.InviteShow = "InviteShow"
AppMsg.UpdateInviteInfo = "UpdateInviteInfo"
AppMsg.InviteDetailShow = "InviteDetailShow"
AppMsg.UpdateInviteDetailInfo = "UpdateInviteDetailInfo"

AppMsg.CashInShow = "CashInShow"
AppMsg.UpdateCashInInfo = "UpdateCashInInfo"
AppMsg.CashoutShow = "CashoutShow"
AppMsg.CashoutRecordShow = "CashoutRecordShow"
AppMsg.UpdateCashoutInfo = "UpdateCashoutInfo"
AppMsg.UpdateCashoutRecords = "UpdateCashoutRecords"
AppMsg.AccountInfoShow = "AccountInfoShow"
AppMsg.ChargeInfoShow = "ChargeInfoShow"
AppMsg.FirshChargeShow = "FirshChargeShow"
AppMsg.CashChannelShow = "CashChannelShow"
AppMsg.UpdateCashChannel = "UpdateCashChannel"
AppMsg.UpdateFirstCharge = "UpdateFirstCharge"


AppCommand = {}
AppCommand.ReconnectGame = "ReconnectGame"
AppCommand.ApplicationPause = "ApplicationPause"
AppCommand.AttributionBack = "AttributionBack"
AppCommand.ActionLoginOut = "ActionLoginOut"
AppCommand.ActionQuitGame = "ActionQuitGame"

AppCommand.ScrollRectContentPositionChanged = "ScrollRectContentPositionChanged"
AppCommand.ScrollRectBeginDrag = "ScrollRectBeginDrag"
AppCommand.ScrollRectEndDrag = "ScrollRectEndDrag"